In [52]:
import tensorflow as tf
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy
import pandas as pd

In [53]:
# reads the data from the file

#df = pd.read_csv('/Users/kaidenjones/Desktop/localify_lab4_data.tsv', sep='\t')
df = pd.read_csv('/Users/cymoar/COMP-ML/Labs/ML-Lab4/localify_music_genre-song_dataset_short_limited.tsv', sep='\t')

# Slpits the data into training and validation data
df_training = df.iloc[:8000]
df_validation = df.iloc[8000:]

# spit the data into labels, X, y
training_label_df = df_training[['song_name','artist_name']]
tensor_label = tf.convert_to_tensor(training_label_df)
training_X_df = df_training[['acousticness','danceability','energy','instrumentalness',
                             'liveness','loudness','speechiness','tempo','valence']]
tensor_training_X = tf.convert_to_tensor(training_X_df)
training_y_df = df_training[['genre_name','Unnamed: 12']]

# tensor_training_y1 = tf.convert_to_tensor(training_y_df[['genre_name']])
tensor_training_y = tf.convert_to_tensor(training_y_df[['Unnamed: 12']], dtype=tf.float32)
tty2 = tf.convert_to_tensor(training_y_df[['Unnamed: 12']])
vector_y = tf.reshape(tty2, [8000])

validation_label_df = df_validation[['song_name','artist_name']]
validation_X_df = df_validation[['acousticness','danceability','energy','instrumentalness','liveness',
                                 'loudness','speechiness','tempo','valence']]
validation_y_df = df_validation[['genre_name','Unnamed: 12']]


In [54]:
# Model archecture
# model = Sequential([
#     Dense(units=25, activation="relu"),
#     Dense(units=15, activation="relu"),
#     Dense(units=10 , activation="linear")])

new_lambda_value = .0001

model = Sequential([
    Dense(units=10, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(new_lambda_value)),
    Dense(units=20, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(new_lambda_value)),
    Dense(units=30, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(new_lambda_value)),
    Dense(units=40, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(new_lambda_value)),
    Dense(units=50, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(new_lambda_value)),
    Dense(units=50, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(new_lambda_value)),
    Dense(units=40, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(new_lambda_value)),
    Dense(units=30, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(new_lambda_value)),
    Dense(units=20, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(new_lambda_value)),
    Dense(units=10 , activation="linear", kernel_regularizer=tf.keras.regularizers.l2(new_lambda_value))])

In [55]:
# gets the loss
#model.compile(optimizer='sgd', loss=SparseCategoricalCrossentropy(from_logits = True))

optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer='adam', loss=SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])


In [56]:
# makes the model fit
model.fit(tensor_training_X, tensor_training_y, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 749us/step - accuracy: 0.1296 - loss: 2.3366
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step - accuracy: 0.1691 - loss: 2.2433
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - accuracy: 0.1734 - loss: 2.2302
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step - accuracy: 0.1706 - loss: 2.2232
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step - accuracy: 0.1739 - loss: 2.2106
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step - accuracy: 0.1656 - loss: 2.2155
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step - accuracy: 0.1624 - loss: 2.2145
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 779us/step - accuracy: 0.1778 - loss: 2.2117
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.1846 - loss: 2.2013
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - accuracy: 0.1830 - loss: 2.1813
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - accuracy: 0.1867 - loss: 2.1856
Epoch 12/100
250/25

In [57]:
# gets the predictions of the model
logits = model(tensor_training_X)
f_x = tf.nn.softmax(logits)

In [58]:
print(f_x)

tf.Tensor(
[[0.10321535 0.0577748  0.17632148 ... 0.16390826 0.02456059 0.05010163]
 [0.2860083  0.05771898 0.01801679 ... 0.13126211 0.20050064 0.01142871]
 [0.2548251  0.10829823 0.01425886 ... 0.0760235  0.11936748 0.02593311]
 ...
 [0.13965507 0.1981784  0.0110024  ... 0.03860742 0.02472048 0.10947231]
 [0.27655447 0.08818203 0.00510556 ... 0.08071852 0.20347516 0.05024549]
 [0.22611989 0.05137041 0.02605849 ... 0.25605905 0.13346729 0.04056448]], shape=(8000, 10), dtype=float32)


In [59]:
predictions = tf.argmax(f_x, axis=1)
sum_vector = tf.reduce_sum(predictions)

In [60]:
correct_predictions = tf.equal(predictions, vector_y)
accuracy = tf.reduce_mean(tf.cast(correct_predictions, tf.float32))
print(correct_predictions)
print(accuracy)
print(vector_y)

tf.Tensor([False  True  True ... False False False], shape=(8000,), dtype=bool)
tf.Tensor(0.3155, shape=(), dtype=float32)
tf.Tensor([0 0 0 ... 5 8 8], shape=(8000,), dtype=int64)


In [61]:
conf_matrix = tf.math.confusion_matrix(labels=vector_y, predictions=predictions)
print(conf_matrix)

tf.Tensor(
[[330 201  84  51   0  25  77 151 132 104]
 [151 415  51  51   0  28  52  57   9 130]
 [ 29   9 671   9   0  10  60  59   2   5]
 [188 251  22 133   0  20  51  47   5  23]
 [201 192  46  33   0  25  40  74  57  69]
 [ 95 190 166  62   0  34  87  90   6  73]
 [ 75 124 266  50   0  26 111  90   3  46]
 [128  28 154  21   0   8  50 301  22  54]
 [163  20  17  10   0   4   6  76 207  15]
 [ 38 182  43  13   0  13  22  58   1 322]], shape=(10, 10), dtype=int32)
