In [1]:
pip install torch torchvision torchaudio

Note: you may need to restart the kernel to use updated packages.


In [2]:
import tensorflow as tf
import numpy as np
# import torch
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy
import pandas as pd

In [7]:
# reads the data from the file
df = pd.read_csv('/Users/kaidenjones/Desktop/localify_lab4_data.tsv', sep='\t')

# Slpits the data into training and validation data
df_training = df.iloc[:8000]
df_validation = df.iloc[8000:]

# spit the data into labels, X, y
training_label_df = df_training[['song_name','artist_name']]
tensor_label = tf.convert_to_tensor(training_label_df)
training_X_df = df_training[['acousticness','danceability','energy','instrumentalness','liveness','loudness','speechiness','tempo','valence']]
tensor_training_X = tf.convert_to_tensor(training_X_df)
training_y_df = df_training[['genre_name','Unnamed: 12']]

# tensor_training_y1 = tf.convert_to_tensor(training_y_df[['genre_name']])
tensor_training_y = tf.convert_to_tensor(training_y_df[['Unnamed: 12']], dtype=tf.float32)



validation_label_df = df_validation[['song_name','artist_name']]
validation_X_df = df_validation[['acousticness','danceability','energy','instrumentalness','liveness','loudness','speechiness','tempo','valence']]
validation_y_df = df_validation[['genre_name','Unnamed: 12']]

# type(df)
# print(df)
# print(training_label_df)
# print(training_X_df)
# print(training_y_df)

# print(validation_label_df)
# print(validation_X_df)
# print(validation_y_df)

In [8]:
# Model archecture
model = Sequential([
    Dense(units=25, activation="relu"),
    Dense(units=15, activation="relu"),
    Dense(units=10 , activation="linear")])

In [9]:
# gets the loss
model.compile(optimizer='sgd', loss=SparseCategoricalCrossentropy(from_logits = True))

In [11]:
# makes the model fit
model.fit(tensor_training_X, tensor_training_y, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 240us/step - loss: 4.5208
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 231us/step - loss: 2.2929
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 231us/step - loss: 2.2885
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 233us/step - loss: 2.2746
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 231us/step - loss: 2.2637
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 230us/step - loss: 2.2490
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 228us/step - loss: 2.2465
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 240us/step - loss: 2.2457
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 230us/step - loss: 2.2376
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 226us/step - loss: 2.2260
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 229us/step - loss: 2.2375
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 229us/step - loss: 2.2335
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 227us/step - loss: 2.2273
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 230us/step - loss: 2.2217
Epoch 15/100
25

In [13]:
# gets the predictions of the model
logits = model(tensor_training_X)
f_x = tf.nn.softmax(logits)

In [14]:
print(f_x)

tf.Tensor(
[[0.12858938 0.1746232  0.05796112 ... 0.08191714 0.0356616  0.10799397]
 [0.15400636 0.08738569 0.1411274  ... 0.10618634 0.07783046 0.0348515 ]
 [0.13322906 0.12005576 0.11510243 ... 0.09696401 0.05501407 0.05445582]
 ...
 [0.11921498 0.20703763 0.03637502 ... 0.07011488 0.02604017 0.15420331]
 [0.11986514 0.2052581  0.037399   ... 0.07082019 0.02654224 0.15126039]
 [0.13172004 0.15639096 0.07347301 ... 0.08765291 0.04161696 0.08738   ]], shape=(8000, 10), dtype=float32)
